/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panaderia;

import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class admin extends javax.swing.JFrame {

    Panaderia con=new Panaderia();
    Connection cn=con.conectar();
    public String nombre_user;
    public admin() {
        initComponents();
        setLocationRelativeTo(null);
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(true);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(false);
//        Calendar c2 = new GregorianCalendar();
//        date_f.setCalendar(c2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A_usuarios = new javax.swing.JPanel();
        B_cedula = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        B_contraseña = new javax.swing.JTextField();
        B_nombre = new javax.swing.JTextField();
        B_apellido = new javax.swing.JTextField();
        B_celular = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        B_nivel = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        B_direccion = new javax.swing.JTextField();
        H_asistencias = new javax.swing.JPanel();
        H_buscar = new javax.swing.JTextField();
        B_buscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_asistencias = new javax.swing.JTable();
        date_f = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        Crear_usuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        apell = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Crear_usuarios = new javax.swing.JButton();
        Historial_asistencias = new javax.swing.JButton();
        Usuarios_administrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        A_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_cedula.setMaximumSize(new java.awt.Dimension(10, 10));
        B_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_cedulaKeyTyped(evt);
            }
        });
        A_usuarios.add(B_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, -1));

        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 70, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        A_usuarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        A_usuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellido:");
        A_usuarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Celular:");
        A_usuarios.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        A_usuarios.add(B_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, -1));
        A_usuarios.add(B_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, -1));
        A_usuarios.add(B_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, -1));
        A_usuarios.add(B_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 170, -1));

        jButton5.setText("Eliminar");
        jButton5.setBorder(null);
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 80, 20));

        B_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario", "admin" }));
        B_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_nivelActionPerformed(evt);
            }
        });
        A_usuarios.add(B_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 130, -1));

        jButton6.setText("Actualizar");
        jButton6.setBorder(null);
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Direccion:");
        A_usuarios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        A_usuarios.add(B_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        getContentPane().add(A_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        H_asistencias.setBackground(new java.awt.Color(51, 51, 51));
        H_asistencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        H_asistencias.add(H_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });
        H_asistencias.add(B_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HISTORIAL DE ASISTENCIAS");
        H_asistencias.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Lista_asistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Fecha", "Hora entrada", "Hora salida"
            }
        ));
        Lista_asistencias.setToolTipText("");
        Lista_asistencias.setEnabled(false);
        jScrollPane2.setViewportView(Lista_asistencias);

        H_asistencias.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 480, 130));

        date_f.setBackground(new java.awt.Color(51, 51, 51));
        date_f.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        date_f.setDateFormatString("dd/MM/yyyy");
        H_asistencias.add(date_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton4.setText("Exportar a Excel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        H_asistencias.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        getContentPane().add(H_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        Crear_usuario.setBackground(new java.awt.Color(51, 51, 51));
        Crear_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Crear_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        Crear_usuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");
        Crear_usuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula");
        Crear_usuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Celular");
        Crear_usuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        Crear_usuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario", "admin" }));
        level.setToolTipText("");
        level.setBorder(null);
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        Crear_usuario.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        jButton1.setText("Crear cuenta");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Crear_usuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        Crear_usuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crear usuario");
        Crear_usuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 60));
        Crear_usuario.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, -1));
        Crear_usuario.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, -1));
        Crear_usuario.add(apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, -1));
        Crear_usuario.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, -1));
        Crear_usuario.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, -1));
        Crear_usuario.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        getContentPane().add(Crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Crear_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        Crear_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Crear_usuarios.setText("Crear usuario");
        Crear_usuarios.setBorder(null);
        Crear_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Crear_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_usuariosActionPerformed(evt);
            }
        });
        jPanel1.add(Crear_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        Historial_asistencias.setText("Historial de asistencias");
        Historial_asistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Historial_asistenciasActionPerformed(evt);
            }
        });
        jPanel1.add(Historial_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        Usuarios_administrar.setText("Usuarios");
        Usuarios_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuarios_administrarActionPerformed(evt);
            }
        });
        jPanel1.add(Usuarios_administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String nombre,apellido,nivel,direc,contraseña,ceduV;
       int cedu,celular;
       nombre = nom.getText();
       apellido=apell.getText();
       nivel=level.getSelectedItem().toString();
       direc=jTextField6.getText();
       contraseña=jTextField1.getText();
       ceduV = jTextField4.getText();
if (nombre.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar el nombre.");
} else if (apellido.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar el apellido.");
} else if (ceduV.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar la cédula.");
} else if (jTextField5.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar el teléfono.");
} else if (direc.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar la dirección.");
} else if (contraseña.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Falta ingresar la contraseña.");
} 
       else if (ceduV.length() != 10) {
        JOptionPane.showMessageDialog(null, "La cédula debe tener exactamente 10 dígitos.");
        }
       else{
        try{
            cedu=Integer.parseInt(jTextField4.getText());
            celular=Integer.parseInt(jTextField5.getText());
            PreparedStatement ps = cn.prepareStatement("INSERT INTO `usuarios`(`nombre`, `apellido`, `cedula`, `celular`, `direccion`, `contraseña`, `nivel`) VALUES (?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setInt(3, cedu);
            ps.setInt(4, celular);
            ps.setString(5, direc);
            ps.setString(6, contraseña);
            ps.setString(7, nivel);
            int rowsInserted = ps.executeUpdate();
            if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente");} 
            else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar el usuario");}
            }catch(java.sql.SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null, "La cédula ya está registrada.");
            }
            catch(Exception e){}
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Historial_asistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Historial_asistenciasActionPerformed
        Historial_asistencias.setBackground(Color.decode("#333333"));
        Historial_asistencias.setForeground(Color.decode("#FFFFFF"));
        Crear_usuarios.setBackground(Color.decode("#FFFFFF"));
        Crear_usuarios.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(false);    
        H_asistencias.setVisible(true);
        A_usuarios.setVisible(false);  
    }//GEN-LAST:event_Historial_asistenciasActionPerformed

    private void Crear_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_usuariosActionPerformed
        Crear_usuarios.setBackground(Color.decode("#333333"));
        Crear_usuarios.setForeground(Color.decode("#FFFFFF"));
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(true);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(false);
    }//GEN-LAST:event_Crear_usuariosActionPerformed

    private void Usuarios_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuarios_administrarActionPerformed
        Usuarios_administrar.setBackground(Color.decode("#333333"));
        Usuarios_administrar.setForeground(Color.decode("#FFFFFF"));
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Crear_usuarios.setBackground(Color.decode("#FFFFFF"));
        Crear_usuarios.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(false);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(true);
    }//GEN-LAST:event_Usuarios_administrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String cedulaIngresada = B_cedula.getText();
    if (cedulaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula.");
    }
    try {
        PreparedStatement ps = cn.prepareStatement("SELECT nombre, apellido, cedula, celular, direccion,contraseña, nivel FROM usuarios WHERE cedula = ?");
        ps.setString(1, cedulaIngresada);
        ResultSet rs = ps.executeQuery();        
        if (rs.next()) {
            B_nombre.setText(rs.getString("nombre"));
            B_apellido.setText(rs.getString("apellido"));
            B_celular.setText(rs.getString("celular"));
            B_direccion.setText(rs.getString("direccion"));        
            B_contraseña.setText(rs.getString("contraseña"));   
            String nivelUsuario = rs.getString("nivel");
            B_nivel.setSelectedItem(nivelUsuario); 
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un usuario con esa cédula.");
        }       
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al buscar el usuario: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed

    }//GEN-LAST:event_levelActionPerformed

    private void B_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_nivelActionPerformed
        
    }//GEN-LAST:event_B_nivelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nivel,celular,direccion,contrasena;
        nivel=B_nivel.getSelectedItem().toString();
        String cedulaIngresada = B_cedula.getText();
        if (cedulaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula.");
    }
        try{
            celular = B_celular.getText();
            direccion = B_direccion.getText();
            contrasena = B_contraseña.getText();
            PreparedStatement ps = cn.prepareStatement("UPDATE usuarios SET nivel = ?,celular = ?,direccion = ?, contraseña = ? WHERE cedula = ?");
            ps.setString(1, nivel);
            ps.setString(2, celular);
            ps.setString(3, direccion);
            ps.setString(4, contrasena);
            ps.setString(5, cedulaIngresada);
            int rowsUpdated = ps.executeUpdate();
            if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Usuario actualizado exitosamente.");
        }
        }catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String cedulaIngresada = B_cedula.getText();
    String[] options = { "si", "no"};
    if (cedulaIngresada.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula para eliminar el usuario.");}
    else {
    var selection = JOptionPane.showOptionDialog(null, "¿Esta seguro que desea eliminar este usuario?", "Mensaje!", 0, 3, null, options, options[0]);
    if (selection == 0) {
      try {
            String sql = "DELETE FROM usuarios WHERE cedula = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, cedulaIngresada);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente.");
                B_nombre.setText("");
                B_apellido.setText("");
                B_cedula.setText("");
                B_celular.setText("");
                B_contraseña.setText("");
                B_direccion.setText("");
                jButton5.setEnabled(false);
                jButton6.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario: " + e.getMessage());
        }
    }
    if (selection == 1) { 
    }
    } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
    String usuario_registro = H_buscar.getText().trim();
    String nombre_user = "";
    Date date = date_f.getDate();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaSeleccionada = (date != null) ? sdf.format(date) : "";

try {
    // Obtener nombre del usuario si se ingresa una cédula específica
    if (!usuario_registro.isEmpty()) {
        String sql = "SELECT nombre FROM usuarios WHERE cedula = ?";
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, usuario_registro);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            nombre_user = rs.getString("nombre");
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no existe");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al obtener usuario: " + e.getMessage());
}

try {
    String sql;
    PreparedStatement ps;

    // Construir la consulta según los filtros
    if (usuario_registro.isEmpty() && fechaSeleccionada.isEmpty()) {
        // Caso 1: Todos los registros
        sql = "SELECT nombre, fecha, hora, hora_salida FROM asistencias";
        ps = cn.prepareStatement(sql);
    } else if (usuario_registro.isEmpty()) {
        // Caso 2: Todos los usuarios en una fecha específica
        sql = "SELECT nombre, fecha, hora, hora_salida FROM asistencias WHERE fecha = ?";
        ps = cn.prepareStatement(sql);
        ps.setString(1, fechaSeleccionada);
    } else if (fechaSeleccionada.isEmpty()) {
        // Caso 3: Un usuario específico en todas las fechas
        sql = "SELECT nombre, fecha, hora, hora_salida FROM asistencias WHERE usuario = ?";
        ps = cn.prepareStatement(sql);
        ps.setString(1, usuario_registro);
    } else {
        // Caso 4: Un usuario específico en una fecha específica
        sql = "SELECT nombre, fecha, hora, hora_salida FROM asistencias WHERE usuario = ? AND fecha = ?";
        ps = cn.prepareStatement(sql);
        ps.setString(1, usuario_registro);
        ps.setString(2, fechaSeleccionada);
    }

    ResultSet prs = ps.executeQuery();

    // Definir las columnas del JTable
    String[] columnNames = {"Usuario", "Fecha", "Hora Entrada", "Hora Salida"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    // Agregar los registros al JTable
    while (prs.next()) {
        String usuario = prs.getString("nombre");
        String fecha = prs.getString("fecha");
        String hora = prs.getString("hora");
        String hora_salida = prs.getString("hora_salida");
        model.addRow(new Object[]{usuario, fecha, hora, hora_salida});
    }

    // Si no hay registros
    if (model.getRowCount() == 0) {
        model.addRow(new Object[]{"No hay asistencias registradas.", "", "", ""});
    }

    // Establecer el modelo en el JTable
    Lista_asistencias.setModel(model);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al obtener el historial de asistencias: " + e.getMessage());
}

    }//GEN-LAST:event_B_buscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void B_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_cedulaKeyTyped
        int key = evt.getKeyChar();
    boolean numeros = key >= 48 && key <= 57;  
    if (!numeros){
        evt.consume();
    }
    if (B_cedula.getText().trim().length() == 10) {
        evt.consume();
    }
    }//GEN-LAST:event_B_cedulaKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Lista_asistencias);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_usuarios;
    private javax.swing.JTextField B_apellido;
    private javax.swing.JButton B_buscar;
    private javax.swing.JTextField B_cedula;
    private javax.swing.JTextField B_celular;
    private javax.swing.JTextField B_contraseña;
    private javax.swing.JTextField B_direccion;
    private javax.swing.JComboBox<String> B_nivel;
    private javax.swing.JTextField B_nombre;
    private javax.swing.JPanel Crear_usuario;
    private javax.swing.JButton Crear_usuarios;
    private javax.swing.JPanel H_asistencias;
    private javax.swing.JTextField H_buscar;
    private javax.swing.JButton Historial_asistencias;
    private javax.swing.JTable Lista_asistencias;
    private javax.swing.JButton Usuarios_administrar;
    private javax.swing.JTextField apell;
    private com.toedter.calendar.JDateChooser date_f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField nom;
    // End of variables declaration//GEN-END:variables
}
