/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panaderia;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static panaderia.login.contraseña;
import static panaderia.login.usuario;

/**
 *
 * @author Administrator
 */
public class usuario extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    Panaderia con=new Panaderia();
    Connection cn=con.conectar();
    public login logged_usuario = new login();
    public String cedula;
    public usuario() { 
        Panaderia con=new Panaderia();
        Connection cn=con.conectar();
        initComponents();
        try {
        String sql = "SELECT nombre, cedula, contraseña, nivel FROM usuarios WHERE cedula = ?";
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, usuario);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            nombre.setText(rs.getString("nombre"));
        }} catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        R_asistencias = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        registro_cedula = new javax.swing.JTextField();
        registro_contraseña = new javax.swing.JPasswordField();
        H_asistencias = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial_asistencias = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Registrar asistencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jButton2.setText("Hisotiral asistencias");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        R_asistencias.setBackground(new java.awt.Color(51, 51, 51));
        R_asistencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton3.setText("Registrar Salida");
        R_asistencias.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 150, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE ASISTENCIA");
        R_asistencias.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jButton4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton4.setText("Registrar Entrada");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        R_asistencias.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        R_asistencias.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula:");
        R_asistencias.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        R_asistencias.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        nombre.setEditable(false);
        R_asistencias.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, -1));
        R_asistencias.add(registro_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, -1));
        R_asistencias.add(registro_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        getContentPane().add(R_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 490, 310));

        H_asistencias.setBackground(new java.awt.Color(51, 51, 51));
        H_asistencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(historial_asistencias);

        H_asistencias.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 390, 190));

        jButton5.setText("Actualizar");
        H_asistencias.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HISTORIAL DE ASISTENCIAS");
        H_asistencias.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        getContentPane().add(H_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 490, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        H_asistencias.setVisible(false);    
        R_asistencias.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        usuario = registro_cedula.getText();
        contraseña = new String(registro_contraseña.getPassword());
        if(usuario.equals("")||contraseña.equals("")){
            JOptionPane.showMessageDialog(null,"Llenar todos los campos");
        }
        else{
            try{
                PreparedStatement ps=cn.prepareStatement("SELECT nivel FROM usuarios WHERE cedula='"+usuario+"' AND contraseña='"+contraseña+"'");
                ResultSet rs=ps.executeQuery();
                if(rs.next()){
                LocalDateTime now = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String fechaHora = now.format(formatter);

                String sqlAsistencia = "INSERT INTO asistencias (usuario, fecha, hora) VALUES (?, ?, ?)";
                PreparedStatement psAsistencia = cn.prepareStatement(sqlAsistencia);

                psAsistencia.setString(1, usuario); 
                psAsistencia.setString(2, fechaHora.split(" ")[0]); 
                psAsistencia.setString(3, fechaHora.split(" ")[1]); 

                int rowsInserted = psAsistencia.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "Ingreso exitoso. Asistencia registrada.");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar la asistencia.");
                }
                    }
                }catch(Exception e){}}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        H_asistencias.setVisible(true);    
        R_asistencias.setVisible(false);
        String usuario_registro = usuario;
        try {
            String sql = "SELECT fecha, hora FROM asistencias WHERE usuario = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, usuario_registro);

            ResultSet rs = ps.executeQuery();

            DefaultListModel<String> modelo = new DefaultListModel<>();

            while (rs.next()) {
                String fecha = rs.getString("fecha");
                String hora = rs.getString("hora");
                modelo.addElement("Fecha: " + fecha + ", Hora: " + hora);
            }

            if (modelo.isEmpty()) {
                modelo.addElement("No hay asistencias registradas para este usuario.");
            }

            historial_asistencias.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al obtener el historial de asistencias: " + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel H_asistencias;
    private javax.swing.JPanel R_asistencias;
    private javax.swing.JList<String> historial_asistencias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField registro_cedula;
    private javax.swing.JPasswordField registro_contraseña;
    // End of variables declaration//GEN-END:variables
}
