/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panaderia;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.DefaultListModel;


/**
 *
 * @author Administrator
 */
public class admin extends javax.swing.JFrame {

    Panaderia con=new Panaderia();
    Connection cn=con.conectar();
    public String nombre_user;
    public admin() {
        initComponents();
        setLocationRelativeTo(null);
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(true);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Crear_usuarios = new javax.swing.JButton();
        Historial_asistencias = new javax.swing.JButton();
        Usuarios_administrar = new javax.swing.JButton();
        Crear_usuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        apell = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        telf = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        level = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        A_usuarios = new javax.swing.JPanel();
        B_cedula = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        B_direccion = new javax.swing.JTextField();
        B_nombre = new javax.swing.JTextField();
        B_apellido = new javax.swing.JTextField();
        B_celular = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        B_nivel = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        H_asistencias = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_asistencias = new javax.swing.JList<>();
        H_buscar = new javax.swing.JTextField();
        B_buscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Crear_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        Crear_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Crear_usuarios.setText("Crear usuario");
        Crear_usuarios.setBorder(null);
        Crear_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Crear_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_usuariosActionPerformed(evt);
            }
        });
        jPanel1.add(Crear_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        Historial_asistencias.setText("Historial de asistencias");
        Historial_asistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Historial_asistenciasActionPerformed(evt);
            }
        });
        jPanel1.add(Historial_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        Usuarios_administrar.setText("Usuarios");
        Usuarios_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuarios_administrarActionPerformed(evt);
            }
        });
        jPanel1.add(Usuarios_administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 40));

        Crear_usuario.setBackground(new java.awt.Color(51, 51, 51));
        Crear_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Crear_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        Crear_usuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");
        Crear_usuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula");
        Crear_usuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Celular");
        Crear_usuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        Crear_usuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        Crear_usuario.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, -1));
        Crear_usuario.add(apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, -1));
        Crear_usuario.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 190, -1));
        Crear_usuario.add(telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, -1));
        Crear_usuario.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, -1));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario", "subadmin", "admin" }));
        level.setToolTipText("");
        level.setBorder(null);
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        Crear_usuario.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        jButton1.setText("Crear cuenta");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Crear_usuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        Crear_usuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        Crear_usuario.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crear usuario");
        Crear_usuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 60));

        jPanel1.add(Crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        A_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        A_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        A_usuarios.add(B_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, -1));

        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 70, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Direccion:");
        A_usuarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        A_usuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellido:");
        A_usuarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Celular:");
        A_usuarios.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        B_direccion.setEditable(false);
        A_usuarios.add(B_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        B_nombre.setEditable(false);
        A_usuarios.add(B_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, -1));

        B_apellido.setEditable(false);
        A_usuarios.add(B_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, -1));

        B_celular.setEditable(false);
        A_usuarios.add(B_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 170, -1));

        jButton5.setText("Eliminar");
        jButton5.setBorder(null);
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 80, 20));

        B_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario", "admin", "subadmin" }));
        B_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_nivelActionPerformed(evt);
            }
        });
        A_usuarios.add(B_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 130, -1));

        jButton6.setText("Actualizar");
        jButton6.setBorder(null);
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        A_usuarios.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, 20));

        jPanel1.add(A_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        H_asistencias.setBackground(new java.awt.Color(51, 51, 51));
        H_asistencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(Lista_asistencias);

        H_asistencias.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 460, -1));
        H_asistencias.add(H_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });
        H_asistencias.add(B_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HISTORIAL DE ASISTENCIAS");
        H_asistencias.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(H_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 530, 280));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String nombre,apellido,nivel,direc,contraseña;
       int cedu,celular;
       nombre = nom.getText();
       apellido=apell.getText();
       nivel=level.getSelectedItem().toString();
       direc=direccion.getText();
       contraseña=pass.getText();
       if (nombre.isEmpty() || apellido.isEmpty() || cedula.getText().isEmpty() || telf.getText().isEmpty() || direc.isEmpty() || contraseña.isEmpty()){
       JOptionPane.showMessageDialog(null,"Llenar todos los campos solicitados");
       }
       else{
        try{
            cedu=Integer.parseInt(cedula.getText());
            celular=Integer.parseInt(telf.getText());
            String sql = "INSERT INTO `usuarios`(`nombre`, `apellido`, `cedula`, `celular`, `direccion`, `contraseña`, `nivel`) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setInt(3, cedu);
            ps.setInt(4, celular);
            ps.setString(5, direc);
            ps.setString(6, contraseña);
            ps.setString(7, nivel);
            int rowsInserted = ps.executeUpdate();
            if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente");} 
            else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar el usuario");}
            }catch(java.sql.SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null, "La cédula ya está registrada.");
            }
            catch(Exception e){}
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Historial_asistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Historial_asistenciasActionPerformed
        Historial_asistencias.setBackground(Color.decode("#333333"));
        Historial_asistencias.setForeground(Color.decode("#FFFFFF"));
        Crear_usuarios.setBackground(Color.decode("#FFFFFF"));
        Crear_usuarios.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(false);    
        H_asistencias.setVisible(true);
        A_usuarios.setVisible(false);  
    }//GEN-LAST:event_Historial_asistenciasActionPerformed

    private void Crear_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_usuariosActionPerformed
        Crear_usuarios.setBackground(Color.decode("#333333"));
        Crear_usuarios.setForeground(Color.decode("#FFFFFF"));
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Usuarios_administrar.setBackground(Color.decode("#FFFFFF"));
        Usuarios_administrar.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(true);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(false);
    }//GEN-LAST:event_Crear_usuariosActionPerformed

    private void Usuarios_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuarios_administrarActionPerformed
        Usuarios_administrar.setBackground(Color.decode("#333333"));
        Usuarios_administrar.setForeground(Color.decode("#FFFFFF"));
        Historial_asistencias.setBackground(Color.decode("#FFFFFF"));
        Historial_asistencias.setForeground(Color.decode("#333333"));
        Crear_usuarios.setBackground(Color.decode("#FFFFFF"));
        Crear_usuarios.setForeground(Color.decode("#333333"));
        Crear_usuario.setVisible(false);    
        H_asistencias.setVisible(false);
        A_usuarios.setVisible(true);
    }//GEN-LAST:event_Usuarios_administrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String cedulaIngresada = B_cedula.getText();
    if (cedulaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula.");
    }
    try {
        String sql = "SELECT nombre, apellido, cedula, celular, direccion, nivel FROM usuarios WHERE cedula = ?";
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, cedulaIngresada);
        ResultSet rs = ps.executeQuery();        
        if (rs.next()) {
            B_nombre.setText(rs.getString("nombre"));
            B_apellido.setText(rs.getString("apellido"));
            B_celular.setText(rs.getString("celular"));
            B_direccion.setText(rs.getString("direccion"));           
            String nivelUsuario = rs.getString("nivel");
            B_nivel.setSelectedItem(nivelUsuario); 
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un usuario con esa cédula.");
        }       
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al buscar el usuario: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed

    }//GEN-LAST:event_levelActionPerformed

    private void B_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_nivelActionPerformed
        
    }//GEN-LAST:event_B_nivelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nivel;
        nivel=B_nivel.getSelectedItem().toString();
        String cedulaIngresada = B_cedula.getText();
        if (cedulaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula.");
    }
        try{
            String sql = "UPDATE usuarios SET nivel = ? WHERE cedula = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, nivel);
            ps.setString(2, cedulaIngresada);
            int rowsUpdated = ps.executeUpdate();
            if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Nivel actualizado exitosamente.");
        }
        }catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String cedulaIngresada = B_cedula.getText();
    String[] options = { "si", "no"};
    if (cedulaIngresada.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, ingresa la cédula para eliminar el usuario.");}
    else {
    var selection = JOptionPane.showOptionDialog(null, "¿Esta seguro que desea eliminar este usuario?", "Let's play a game!", 0, 3, null, options, options[0]);
    if (selection == 0) {
      try {
            String sql = "DELETE FROM usuarios WHERE cedula = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, cedulaIngresada);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente.");
                B_nombre.setText("");
                B_apellido.setText("");
                B_cedula.setText("");
                B_celular.setText("");
                B_direccion.setText("");
                jButton5.setEnabled(false);
                jButton6.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario: " + e.getMessage());
        }
    }
    if (selection == 1) { 
    }
    } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
        String usuario_registro = H_buscar.getText();
        try {
        String sql = "SELECT nombre, cedula, contraseña, nivel FROM usuarios WHERE cedula = ?";
        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, usuario_registro);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            nombre_user=rs.getString("nombre");
        }} catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
    }
        try {
            String sql = "SELECT fecha, hora,hora_salida FROM asistencias WHERE usuario = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, usuario_registro);

            ResultSet rs = ps.executeQuery();

            DefaultListModel<String> modelo = new DefaultListModel<>();

            while (rs.next()) {
                String fecha = rs.getString("fecha");
                String hora = rs.getString("hora");
                String hora_salida = rs.getString("hora_salida");
                modelo.addElement("User: "+nombre_user+" ||Fecha: " + fecha + " ||Hora: " + hora+" ||Hora Salida: "+ hora_salida);
            }

            if (modelo.isEmpty()) {
                modelo.addElement("No hay asistencias registradas para este usuario.");
            }

            Lista_asistencias.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al obtener el historial de asistencias: " + e);
        }
    }//GEN-LAST:event_B_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_usuarios;
    private javax.swing.JTextField B_apellido;
    private javax.swing.JButton B_buscar;
    private javax.swing.JTextField B_cedula;
    private javax.swing.JTextField B_celular;
    private javax.swing.JTextField B_direccion;
    private javax.swing.JComboBox<String> B_nivel;
    private javax.swing.JTextField B_nombre;
    private javax.swing.JPanel Crear_usuario;
    private javax.swing.JButton Crear_usuarios;
    private javax.swing.JPanel H_asistencias;
    private javax.swing.JTextField H_buscar;
    private javax.swing.JButton Historial_asistencias;
    private javax.swing.JList<String> Lista_asistencias;
    private javax.swing.JButton Usuarios_administrar;
    private javax.swing.JTextField apell;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField telf;
    // End of variables declaration//GEN-END:variables
}
